#!/usr/bin/env python3

"""
WiSec - Network Security Visualization

Visualizes real data generated by the WiSec project.

Data sources:
    1. devices.db
       - Device information
       - Vendor information
       - Device type
       - Online/offline status
       - Connection history

    2. logs/scan_*.json
       - Port scan results
       - Open ports
       - Services

Libraries:
    NumPy
    Matplotlib
    SQLite
    JSON

Run:
    python3 visualization.py
"""

import os
import glob
import json
import sqlite3
from datetime import datetime

import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# PROJECT PATHS
# ============================================================

# Get the folder where visualization.py is located.
# This makes the program independent of the current terminal
# working directory.

BASE_DIR = os.path.dirname(
    os.path.abspath(__file__)
)

DB_PATH = os.path.join(
    BASE_DIR,
    "devices.db"
)

LOG_DIR = os.path.join(
    BASE_DIR,
    "logs"
)


# ============================================================
# LOAD DEVICE DATA FROM SQLITE
# ============================================================

def load_devices():

    if not os.path.exists(DB_PATH):

        print("[!] devices.db not found.")
        print("[!] Run history_tracker.py first.")

        return []

    try:

        conn = sqlite3.connect(
            DB_PATH
        )

        cursor = conn.execute("""
            SELECT
                mac,
                ip,
                vendor,
                hostname,
                device_type,
                is_online,
                first_seen,
                last_seen
            FROM devices
        """)

        rows = cursor.fetchall()

        conn.close()

    except sqlite3.Error as error:

        print(
            f"[!] Database error: {error}"
        )

        return []

    devices = []

    for row in rows:

        devices.append({

            "mac": row[0],

            "ip": row[1],

            "vendor": (
                row[2]
                if row[2]
                else "Unknown"
            ),

            "hostname": (
                row[3]
                if row[3]
                else "Unknown"
            ),

            "device_type": (
                row[4]
                if row[4]
                else "Unknown"
            ),

            "is_online": (
                row[5]
                if row[5] is not None
                else 0
            ),

            "first_seen": row[6],

            "last_seen": row[7]
        })

    return devices


# ============================================================
# DEVICE TYPE ANALYSIS
# ============================================================

def get_device_types(devices):

    if not devices:

        return {}

    types = np.array([

        device["device_type"]
        if device["device_type"]
        else "Unknown"

        for device in devices

    ])

    unique_types, counts = np.unique(
        types,
        return_counts=True
    )

    return dict(
        zip(
            unique_types,
            counts
        )
    )


# ============================================================
# VENDOR ANALYSIS
# ============================================================

def get_vendors(devices):

    if not devices:

        return {}

    vendors = np.array([

        device["vendor"]
        if device["vendor"]
        else "Unknown"

        for device in devices

    ])

    unique_vendors, counts = np.unique(
        vendors,
        return_counts=True
    )

    return dict(
        zip(
            unique_vendors,
            counts
        )
    )


# ============================================================
# ONLINE / OFFLINE DATA
# ============================================================

def get_online_status(devices):

    if not devices:

        return 0, 0

    status = np.array([

        device["is_online"]

        for device in devices

    ])

    online = np.sum(
        status == 1
    )

    offline = np.sum(
        status == 0
    )

    return (
        int(online),
        int(offline)
    )


# ============================================================
# FIND LATEST PORT SCAN
# ============================================================

def load_latest_port_scan():

    pattern = os.path.join(
        LOG_DIR,
        "scan_*.json"
    )

    files = glob.glob(
        pattern
    )

    if not files:

        print(
            "[!] No port scan JSON files found."
        )

        return None

    # Files contain timestamps in their names.
    # Sorting allows us to select the latest scan.

    files.sort()

    latest_file = files[-1]

    try:

        with open(
            latest_file,
            "r",
            encoding="utf-8"
        ) as file:

            data = json.load(file)

        print(
            f"[+] Latest port scan:"
            f" {os.path.basename(latest_file)}"
        )

        return data

    except (
        OSError,
        json.JSONDecodeError
    ) as error:

        print(
            f"[!] Error reading port scan: {error}"
        )

        return None


# ============================================================
# OPEN PORT ANALYSIS
# ============================================================

def get_port_data(scan_data):

    port_counts = {}

    if not scan_data:

        return port_counts

    results = scan_data.get(
        "results",
        []
    )

    for host in results:

        open_ports = host.get(
            "open_ports",
            []
        )

        for port_info in open_ports:

            port = str(
                port_info.get(
                    "port",
                    "Unknown"
                )
            )

            port_counts[port] = (
                port_counts.get(
                    port,
                    0
                ) + 1
            )

    return port_counts


# ============================================================
# CONNECTION HISTORY
# ============================================================

def load_connection_history():

    if not os.path.exists(DB_PATH):

        return []

    try:

        conn = sqlite3.connect(
            DB_PATH
        )

        cursor = conn.execute("""
            SELECT
                mac,
                connected_at,
                disconnected_at
            FROM connection_history
            ORDER BY connected_at
        """)

        rows = cursor.fetchall()

        conn.close()

        return rows

    except sqlite3.Error as error:

        print(
            f"[!] Connection history error: {error}"
        )

        return []


# ============================================================
# CREATE NETWORK ACTIVITY DATA
# ============================================================

def get_network_activity():

    rows = load_connection_history()

    if not rows:

        return (
            np.array([]),
            np.array([])
        )

    events = []

    for row in rows:

        mac = row[0]
        connected_at = row[1]
        disconnected_at = row[2]

        # Device connected

        if connected_at:

            try:

                timestamp = datetime.fromisoformat(
                    connected_at
                )

                events.append(
                    (
                        timestamp,
                        1,
                        mac
                    )
                )

            except ValueError:
                pass

        # Device disconnected

        if disconnected_at:

            try:

                timestamp = datetime.fromisoformat(
                    disconnected_at
                )

                events.append(
                    (
                        timestamp,
                        -1,
                        mac
                    )
                )

            except ValueError:
                pass

    if not events:

        return (
            np.array([]),
            np.array([])
        )

    # Sort events chronologically

    events.sort(
        key=lambda x: x[0]
    )

    timestamps = []
    online_counts = []

    current_online = 0

    for timestamp, change, mac in events:

        current_online += change

        # Prevent negative values if the database
        # contains an unusual event sequence.

        current_online = max(
            current_online,
            0
        )

        timestamps.append(
            timestamp
        )

        online_counts.append(
            current_online
        )

    return (
        np.array(timestamps),
        np.array(online_counts)
    )


# ============================================================
# DEVICE TYPE BAR CHART
# ============================================================

def plot_device_types(
    ax,
    data
):

    if not data:

        ax.text(
            0.5,
            0.5,
            "No device data available",
            ha="center",
            va="center"
        )

        ax.set_title(
            "Device Type Distribution"
        )

        return

    labels = np.array(
        list(data.keys())
    )

    values = np.array(
        list(data.values())
    )

    bars = ax.bar(
        labels,
        values
    )

    ax.set_title(
        "Device Type Distribution"
    )

    ax.set_xlabel(
        "Device Type"
    )

    ax.set_ylabel(
        "Number of Devices"
    )

    ax.tick_params(
        axis="x",
        rotation=30
    )

    # Display values above bars

    for bar, value in zip(
        bars,
        values
    ):

        ax.text(
            bar.get_x()
            + bar.get_width() / 2,

            value,

            str(value),

            ha="center",
            va="bottom"
        )


# ============================================================
# VENDOR PIE CHART
# ============================================================

def plot_vendors(
    ax,
    data
):

    if not data:

        ax.text(
            0.5,
            0.5,
            "No vendor data available",
            ha="center",
            va="center"
        )

        ax.set_title(
            "Vendor Distribution"
        )

        return

    labels = np.array(
        list(data.keys())
    )

    values = np.array(
        list(data.values())
    )

    # If there are many vendors,
    # keep the seven largest and group
    # the remaining vendors into "Others".

    if len(values) > 8:

        order = np.argsort(
            values
        )

        largest = order[-7:]

        other_count = np.sum(
            values[order[:-7]]
        )

        new_labels = list(
            labels[largest]
        )

        new_values = list(
            values[largest]
        )

        if other_count > 0:

            new_labels.append(
                "Others"
            )

            new_values.append(
                other_count
            )

        labels = np.array(
            new_labels
        )

        values = np.array(
            new_values
        )

    ax.pie(
        values,
        labels=labels,
        autopct="%1.1f%%",
        startangle=90
    )

    ax.set_title(
        "Vendor Distribution"
    )


# ============================================================
# OPEN PORT BAR CHART
# ============================================================

def plot_ports(
    ax,
    port_data
):

    if not port_data:

        ax.text(
            0.5,
            0.5,
            "No open ports found",
            ha="center",
            va="center"
        )

        ax.set_title(
            "Open Ports"
        )

        return

    ports = np.array(
        list(port_data.keys())
    )

    counts = np.array(
        list(port_data.values())
    )

    # Sort ports numerically

    try:

        order = np.argsort(
            ports.astype(int)
        )

        ports = ports[order]

        counts = counts[order]

    except ValueError:

        pass

    bars = ax.bar(
        ports,
        counts
    )

    ax.set_title(
        "Open Ports"
    )

    ax.set_xlabel(
        "Port Number"
    )

    ax.set_ylabel(
        "Number of Hosts"
    )

    for bar, value in zip(
        bars,
        counts
    ):

        ax.text(
            bar.get_x()
            + bar.get_width() / 2,

            value,

            str(value),

            ha="center",
            va="bottom"
        )


# ============================================================
# NETWORK ACTIVITY LINE CHART
# ============================================================

def plot_network_activity(ax):

    timestamps, online_counts = (
        get_network_activity()
    )

    if len(timestamps) == 0:

        ax.text(
            0.5,
            0.5,
            "No connection history available",
            ha="center",
            va="center"
        )

        ax.set_title(
            "Network Activity"
        )

        return

    # If there are many events, display
    # only the most recent 50.

    if len(timestamps) > 50:

        timestamps = timestamps[-50:]

        online_counts = online_counts[-50:]

    x = np.arange(
        len(timestamps)
    )

    ax.plot(
        x,
        online_counts,
        marker="o"
    )

    ax.set_title(
        "Network Activity"
    )

    ax.set_xlabel(
        "Connection Events"
    )

    ax.set_ylabel(
        "Online Devices"
    )

    # Make the X-axis readable

    if len(timestamps) <= 12:

        ax.set_xticks(
            x
        )

        ax.set_xticklabels(
            [
                timestamp.strftime(
                    "%H:%M:%S"
                )

                for timestamp in timestamps
            ],

            rotation=30
        )


# ============================================================
# MAIN
# ============================================================

def main():

    print()
    print(
        "=" * 60
    )

    print(
        "        WiSec - Network Visualization"
    )

    print(
        "=" * 60
    )

    print()

    # --------------------------------------------------------
    # LOAD DEVICES
    # --------------------------------------------------------

    devices = load_devices()

    if not devices:

        print(
            "[!] No devices found in devices.db."
        )

        print(
            "[!] Run history_tracker.py first."
        )

        return

    # --------------------------------------------------------
    # ANALYZE DEVICES
    # --------------------------------------------------------

    device_data = get_device_types(
        devices
    )

    vendor_data = get_vendors(
        devices
    )

    online_count, offline_count = (
        get_online_status(
            devices
        )
    )

    # --------------------------------------------------------
    # LOAD PORT SCAN
    # --------------------------------------------------------

    port_scan = (
        load_latest_port_scan()
    )

    port_data = get_port_data(
        port_scan
    )

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    total_devices = len(
        devices
    )

    total_open_ports = sum(
        port_data.values()
    )

    print(
        f"[+] Total devices : "
        f"{total_devices}"
    )

    print(
        f"[+] Online        : "
        f"{online_count}"
    )

    print(
        f"[+] Offline       : "
        f"{offline_count}"
    )

    print(
        f"[+] Open ports    : "
        f"{total_open_ports}"
    )

    print()

    # ========================================================
    # CREATE DASHBOARD
    # ========================================================

    fig, axes = plt.subplots(
        2,
        2,
        figsize=(15, 9)
    )

    fig.suptitle(
        "WiSec - Network Security Monitor",
        fontsize=20,
        fontweight="bold"
    )

    # --------------------------------------------------------
    # 1. DEVICE TYPES
    # --------------------------------------------------------

    plot_device_types(
        axes[0, 0],
        device_data
    )

    # --------------------------------------------------------
    # 2. VENDORS
    # --------------------------------------------------------

    plot_vendors(
        axes[0, 1],
        vendor_data
    )

    # --------------------------------------------------------
    # 3. OPEN PORTS
    # --------------------------------------------------------

    plot_ports(
        axes[1, 0],
        port_data
    )

    # --------------------------------------------------------
    # 4. NETWORK ACTIVITY
    # --------------------------------------------------------

    plot_network_activity(
        axes[1, 1]
    )

    # --------------------------------------------------------
    # SUMMARY AT BOTTOM
    # --------------------------------------------------------

    fig.text(

        0.5,
        0.015,

        (
            f"Devices: {total_devices}"
            f"    |    "
            f"Online: {online_count}"
            f"    |    "
            f"Offline: {offline_count}"
            f"    |    "
            f"Open Ports: {total_open_ports}"
        ),

        ha="center",

        fontsize=12
    )

    # --------------------------------------------------------
    # LAYOUT
    # --------------------------------------------------------

    plt.tight_layout(
        rect=[
            0,
            0.04,
            1,
            0.95
        ]
    )

    print(
        "[+] Visualization ready."
    )

    print(
        "[+] Close the graph window to exit."
    )

    # --------------------------------------------------------
    # DISPLAY
    # --------------------------------------------------------

    plt.show()


# ============================================================
# PROGRAM START
# ============================================================

if __name__ == "__main__":

    main()
